# Explorative Data Analysis

In this notebook, we will have a closer look on the energy production data of Germany between 2015 - 2025 provided by SMARD.
The goal is to observe how energy production developed over the years in Germany, especially the development of the different methods of energy production.

## 1. Raw Data

In [1]:
import pandas as pd

In [9]:
df_raw = pd.read_csv("../data/raw/Realisierte_Erzeugung_201501010000_202601010000_Monat.csv")
df_raw.head()

                                                                                                                                                                         Datum von;Datum bis;Biomasse [MWh] Berechnete Auflösungen;Wasserkraft [MWh] Berechnete Auflösungen;Wind Offshore [MWh] Berechnete Auflösungen;Wind Onshore [MWh] Berechnete Auflösungen;Photovoltaik [MWh] Berechnete Auflösungen;Sonstige Erneuerbare [MWh] Berechnete Auflösungen;Kernenergie [MWh] Berechnete Auflösungen;Braunkohle [MWh] Berechnete Auflösungen;Steinkohle [MWh] Berechnete Auflösungen;Erdgas [MWh] Berechnete Auflösungen;Pumpspeicher [MWh] Berechnete Auflösungen;Sonstige Konventionelle [MWh] Berechnete Auflösungen
01.01.2015;01.02.2015;3.479.938 77;1.186.617 59;264.490 14;9.404.178 83;560.194   61;175.611 97;8.201.762 38;11.800.183 18;6.387.685 58;1.405.688 92;762.023 04;839.702                                               19.0
01.02.2015;01.03.2015;3.153.613 46;871.004   80;284.790 22;5.181.228 19;1.367.809 39;154.664 97;7.498.808 73;11.249.755 30;7.886.895 71;1.615.352 60;651.887 77;797.723                                               97.0
01.03.2015;01.04.2015;3.437.602 13;1.030.917 99;434.443 05;6.865.747 54;2.839.770 88;156.243 35;7.308.641 32;12.177.183 02;7.320.063 65;1.359.908 55;718.934 49;817.338                                               79.0
01.04.2015;01.05.2015;3.269.723 30;1.248.928 32;379.940 40;4.837.677 66;4.380.466 76;151.245 19;6.858.356 45;10.200.743 22;5.994.324 95;850.196   84;676.779 64;770.986                                               52.0
01.05.2015;01.06.2015;3.361.025 36;1.560.655 41;566.551 40;4.848.138 13;4.366.740 00;136.081 97;6.930.784 48;8.935.798  05;4.295.091 75;866.135   02;747.062 94;714.053                                               44.0

The columns in the csv-file are seperated with ";". This leads into a dataframe with only one column. The code needs to be adjusted, so that the columns can be separated as intended.

In [19]:
df_raw2 = pd.read_csv("../data/raw/Realisierte_Erzeugung_201501010000_202601010000_Monat.csv", sep=";")
df_raw2.head()

,Datum von,Datum bis,Biomasse [MWh] Berechnete Auflösungen,Wasserkraft [MWh] Berechnete Auflösungen,Wind Offshore [MWh] Berechnete Auflösungen,Wind Onshore [MWh] Berechnete Auflösungen,Photovoltaik [MWh] Berechnete Auflösungen,Sonstige Erneuerbare [MWh] Berechnete Auflösungen,Kernenergie [MWh] Berechnete Auflösungen,Braunkohle [MWh] Berechnete Auflösungen,Steinkohle [MWh] Berechnete Auflösungen,Erdgas [MWh] Berechnete Auflösungen,Pumpspeicher [MWh] Berechnete Auflösungen,Sonstige Konventionelle [MWh] Berechnete Auflösungen
0,01.01.2015,01.02.2015,"3.479.938,77","1.186.617,59","264.490,14","9.404.178,83","560.194,61","175.611,97","8.201.762,38","11.800.183,18","6.387.685,58","1.405.688,92","762.023,04","839.702,19"
1,01.02.2015,01.03.2015,"3.153.613,46","871.004,80","284.790,22","5.181.228,19","1.367.809,39","154.664,97","7.498.808,73","11.249.755,30","7.886.895,71","1.615.352,60","651.887,77","797.723,97"
2,01.03.2015,01.04.2015,"3.437.602,13","1.030.917,99","434.443,05","6.865.747,54","2.839.770,88","156.243,35","7.308.641,32","12.177.183,02","7.320.063,65","1.359.908,55","718.934,49","817.338,79"
3,01.04.2015,01.05.2015,"3.269.723,30","1.248.928,32","379.940,40","4.837.677,66","4.380.466,76","151.245,19","6.858.356,45","10.200.743,22","5.994.324,95","850.196,84","676.779,64","770.986,52"
4,01.05.2015,01.06.2015,"3.361.025,36","1.560.655,41","566.551,40","4.848.138,13","4.366.740,00","136.081,97","6.930.784,48","8.935.798,05","4.295.091,75","866.135,02","747.062,94","714.053,44"

In [20]:
df_raw2.tail()

,Datum von,Datum bis,Biomasse [MWh] Berechnete Auflösungen,Wasserkraft [MWh] Berechnete Auflösungen,Wind Offshore [MWh] Berechnete Auflösungen,Wind Onshore [MWh] Berechnete Auflösungen,Photovoltaik [MWh] Berechnete Auflösungen,Sonstige Erneuerbare [MWh] Berechnete Auflösungen,Kernenergie [MWh] Berechnete Auflösungen,Braunkohle [MWh] Berechnete Auflösungen,Steinkohle [MWh] Berechnete Auflösungen,Erdgas [MWh] Berechnete Auflösungen,Pumpspeicher [MWh] Berechnete Auflösungen,Sonstige Konventionelle [MWh] Berechnete Auflösungen
127,01.08.2025,01.09.2025,"2.852.499,35","1.463.011,45","1.699.077,95","5.459.159,51","9.672.278,48","73.973,16",-,"4.518.747,75","1.301.445,00","3.015.974,75","843.045,25","1.075.939,50"
128,01.09.2025,01.10.2025,"2.794.210,42","1.208.876,63","2.410.541,28","9.721.142,41","6.435.895,39","72.157,99",-,"4.925.688,75","1.397.569,00","3.790.773,75","733.651,25","1.014.139,00"
129,01.10.2025,01.11.2025,"3.034.056,45","1.116.769,65","2.901.834,16","13.695.534,40","3.642.622,45","79.788,30",-,"5.648.721,13","2.166.156,53","5.275.413,52","756.737,01","1.394.098,94"
130,01.11.2025,01.12.2025,"3.069.622,61","1.084.135,10","2.716.300,26","9.952.192,85","2.210.900,10","81.528,93",-,"6.595.504,11","3.165.924,61","7.519.788,06","673.562,25","1.350.662,80"
131,01.12.2025,01.01.2026,"3.193.590,01","1.022.205,69","3.425.383,69","12.474.033,51","1.509.063,85","88.217,82",-,"5.444.634,18","2.599.886,52","7.523.775,97","719.716,35","1.429.378,01"

#### First Impressions

1. Each row showcases the amount of energy that has been produced in that month. 2 columns give the timeframe of said production: First and last day of the month in the given year.
2. Since provided data is from SMARD, default language is German.
3. Numbers for energy production are seperated every thousandth digit with a ".". Decimals are separated with ",".
4. The available energy prdoctions can be separated into 2 groups: Renewable and conventionel energy.
5. For "Kernenergie", there are no values in the last 5 rows. This needs to be looked at further

In [21]:
df_raw2[["Kernenergie [MWh] Berechnete Auflösungen", "Datum von"]]

    Kernenergie [MWh] Berechnete Auflösungen   Datum von
0                               8.201.762,38  01.01.2015
1                               7.498.808,73  01.02.2015
2                               7.308.641,32  01.03.2015
3                               6.858.356,45  01.04.2015
4                               6.930.784,48  01.05.2015
..                                       ...         ...
127                                        -  01.08.2025
128                                        -  01.09.2025
129                                        -  01.10.2025
130                                        -  01.11.2025
131                                        -  01.12.2025

[132 rows x 2 columns]

Starting May/2023, nuclear energy production is 0. It also gets changed into a "-" starting the year 2024. The reason for this is that Germany decided on June 30 2011 to exit from nuclear energy prodcution completely after the catastrophe in Fukushima/Japan on March 11 2011. The last 3 nuclear reactors were shut down on April 15 2023.

In [22]:
df_raw2.isna().sum()

Datum von                                               0
Datum bis                                               0
Biomasse [MWh] Berechnete Auflösungen                   0
Wasserkraft [MWh] Berechnete Auflösungen                0
Wind Offshore [MWh] Berechnete Auflösungen              0
Wind Onshore [MWh] Berechnete Auflösungen               0
Photovoltaik [MWh] Berechnete Auflösungen               0
Sonstige Erneuerbare [MWh] Berechnete Auflösungen       0
Kernenergie [MWh] Berechnete Auflösungen                0
Braunkohle [MWh] Berechnete Auflösungen                 0
Steinkohle [MWh] Berechnete Auflösungen                 0
Erdgas [MWh] Berechnete Auflösungen                     0
Pumpspeicher [MWh] Berechnete Auflösungen               0
Sonstige Konventionelle [MWh] Berechnete Auflösungen    0
dtype: int64

There don't seem to be any missing data. But since "-" is used on nuclear energy, dataframe will be updatet to include "-" as missing data.

In [23]:
df_raw3 = pd.read_csv("../data/raw/Realisierte_Erzeugung_201501010000_202601010000_Monat.csv", sep=";", na_values="-")
df_raw3.isna().sum()

Datum von                                                0
Datum bis                                                0
Biomasse [MWh] Berechnete Auflösungen                    0
Wasserkraft [MWh] Berechnete Auflösungen                 0
Wind Offshore [MWh] Berechnete Auflösungen               0
Wind Onshore [MWh] Berechnete Auflösungen                0
Photovoltaik [MWh] Berechnete Auflösungen                0
Sonstige Erneuerbare [MWh] Berechnete Auflösungen        0
Kernenergie [MWh] Berechnete Auflösungen                24
Braunkohle [MWh] Berechnete Auflösungen                  0
Steinkohle [MWh] Berechnete Auflösungen                  0
Erdgas [MWh] Berechnete Auflösungen                      0
Pumpspeicher [MWh] Berechnete Auflösungen                0
Sonstige Konventionelle [MWh] Berechnete Auflösungen     0
dtype: int64